# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:

trigger:
  batch: true
  branches:
    include:
    - master
    - releases/*

pool:
#  name: 'Binocus'
  demands:
    - msbuild

steps:
- checkout: self
  clean: true
  fetchDepth: 1
  submodules: recursive

- task: NuGetToolInstaller@1
  inputs:
    checkLatest: true

- task: CMake@1
  inputs:
    workingDirectory: '.'
    cmakeArgs: '-S . -B ./build -G "Visual Studio 16 2019"'
  displayName: 'cmake'

- task: MSBuild@1
  inputs:
    solution: 'build/OpenCV.sln'
    msbuildArchitecture: 'x64'
    configuration: 'Release'

- task: MSBuild@1
  inputs:
    solution: 'build/OpenCV.sln'
    msbuildArchitecture: 'x64'
    configuration: 'Debug'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'package\nuget\OpenCV.nuspec'
    versioningScheme: 'off'