name: Push Build

on:
  push:

env:
  cuda: "10.2.89"
  opencv_contrib_ref: '3.4.15'

runs-on: windows-latest
timeout-minutes: 360

steps:
- name: Checkout OpenCV
  uses: actions/checkout@v2
  with:
    clean: true
    fetch-depth: 1
    path: opencv

- name: Checkout OpenCV_Contrib
  uses: actions/checkout@v2
  with:
    repository: opencv/opencv_contrib
    clean: true
    fetch-depth: 1
    path: opencv_contrib
    ref: ${{ env.opencv_contrib_ref }}

- name: Setup MSVC
  uses: ilammy/msvc-dev-cmd@v1.9.0
  #with:
  #  arch: amd64
  #  toolset: 16.0

- name: Install CUDA
  uses: Jimver/cuda-toolkit@v0.2.4
  id: cuda-toolkit
  with:
    cuda: ${{ env.cuda }}

- name: nvcc check
  shell: powershell
  run: |
    nvcc -V
    ls $env:CUDA_PATH
    ls $env:CUDA_PATH\bin
    ls $env:CUDA_PATH\include

- name: CMake
  run: cmake -DWITH_CUDA=ON -DENABLE_FAST_MATH=1 -DCUDA_FAST_MATH=1 -DWITH_CUBLAS=1 -DBUILD_WITH_DEBUG_INFO=OFF -DBUILD_PACKAGE=OFF -DBUILD_JAVA=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_DOCS=OFF -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF -DINSTALL_C_EXAMPLES=OFF -DINSTALL_TESTS=OFF -DOPENCV_EXTRA_MODULES_PATH=opencv_contrib/modules -S opencv -B build -G "Visual Studio 16 2019"

- name: Build Release
  working-directory: ./build
  run: msbuild /m /p:Configuration=Release OpenCV.sln

- name: nuget pack for non-tags
  working-directory: opencv
  if: "!startswith(github.ref, 'refs/tags/')"
  run: |
    echo Branch: ${GITHUB_REF##*/}
    nuget pack package\nuget\opencv.nuspec -version 1.0.0-dev -outputfilenameswithoutversion -outputdirectory dist -Properties branch=${GITHUB_REF##*/} -Properties commit=${{ github.sha }}

- name: upload package artifact
  uses: actions/upload-artifact@v2
  with:
    name: nuget
    path: opencv\dist\*.nupkg

- name: extract tag name
  if: startswith(github.ref, 'refs/tags/')
  uses: olegtarasov/get-tag@v2.1.1
  id: tagname

- name: nuget pack/push for tags
  if: startswith(github.ref, 'refs/tags/')
  working-directory: opencv
  run: |
    nuget pack package\nuget\opencv.nuspec -version ${{env.git_tag_name}} -outputfilenameswithoutversion -outputdirectory dist -Properties branch=${{env.git_tag_name}} -Properties commit=${{ github.sha }}
    nuget push dist\wuganhao.opencv.nupkg -apikey ${{secrets.nuget_api_key}} -source https://api.nuget.org/v3/index.json