name: Push Build

on:
  push:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        clean: true
        fetch-depth: 1

    - name: Setup NuGet
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      #with:
      #  arch: amd64
      #  toolset: 16.0

    - name: CMake
      working-directory: .
      run: cmake -S . -B ./build -G "Visual Studio 16 2019"

    - name: Build Release
      working-directory: ./build
      run: msbuild /m /p:Configuration=Release OpenCV.sln

    - name: Build Debug
      working-directory: ./build
      run: msbuild /m /p:Configuration=Debug OpenCV.sln
